/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard.quotes'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard.requests'
import { Route as DashboardVerificationRouteImport } from './routes/dashboard.verification'
import { Route as MarketplaceProductIdRouteImport } from './routes/marketplace.$productId'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerificationRoute = DashboardVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketplaceProductIdRoute = MarketplaceProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RequestsRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/dashboard'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/marketplace'
    | '/onboarding'
    | '/register'
    | '/request'
    | '/requests'
    | '/suppliers'
    | '/dashboard/analytics'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/quotes'
    | '/dashboard/requests'
    | '/dashboard/verification'
    | '/marketplace/$productId'
    | '/requests/$id'
    | '/suppliers/$id'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/marketplace'
    | '/onboarding'
    | '/register'
    | '/request'
    | '/requests'
    | '/suppliers'
    | '/dashboard/analytics'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/quotes'
    | '/dashboard/requests'
    | '/dashboard/verification'
    | '/marketplace/$productId'
    | '/requests/$id'
    | '/suppliers/$id'
    | '/admin'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/dashboard'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/marketplace'
    | '/onboarding'
    | '/register'
    | '/request'
    | '/requests'
    | '/suppliers'
    | '/dashboard/analytics'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/quotes'
    | '/dashboard/requests'
    | '/dashboard/verification'
    | '/marketplace/$productId'
    | '/requests/$id'
    | '/suppliers/$id'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  RequestRoute: typeof RequestRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  SuppliersRoute: typeof SuppliersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verification': {
      id: '/dashboard/verification'
      path: '/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof DashboardVerificationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/marketplace/$productId': {
      id: '/marketplace/$productId'
      path: '/$productId'
      fullPath: '/marketplace/$productId'
      preLoaderRoute: typeof MarketplaceProductIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardVerificationRoute: typeof DashboardVerificationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardVerificationRoute: DashboardVerificationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceProductIdRoute: typeof MarketplaceProductIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceProductIdRoute: MarketplaceProductIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface RequestsRouteChildren {
  RequestsIdRoute: typeof RequestsIdRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsIdRoute: RequestsIdRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRouteWithChildren,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  RequestRoute: RequestRoute,
  RequestsRoute: RequestsRouteWithChildren,
  SuppliersRoute: SuppliersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
